baseURL = 'https://muscat-tech.org/'
languageCode = 'en'
title = 'Muscat Tech'
theme= 'muscat-tech'



[permalinks]
  [permalinks.page]
    events = '/groups/:sections[last]/events/:year/:month/:slug/'
  [permalinks.section]
    events = '/groups/:sections[last]/'
